"""
Isolated Long Châu diagnostic runner.

This file intentionally does NOT modify any production crawler code.
It runs the existing crawl_longchau() and also performs a separate
raw-API diagnostic to identify why API items may be dropped by the
current Long Châu API dedupe.

Run:
    python test_longchau.py

Optional:
    python test_longchau.py https://nhathuoclongchau.com.vn/he-thong-cua-hang/ho-chi-minh

The test is intentionally limited to Long Châu so existing KFC,
Lotteria, DMX, TGDD, FPT Shop, Pharmacity and BHX crawlers are untouched.
"""

import asyncio
import re
import sys

from playwright.async_api import async_playwright

from brands.retail import (
    LONGCHAU_STORE_API,
    crawl_longchau,
    normalize_text,
)
from dedupe import dedupe_records


DEFAULT_URL = (
    "https://nhathuoclongchau.com.vn/he-thong-cua-hang/ho-chi-minh"
)


def print_log_lines(logs):
    print("\n" + "=" * 100)
    print("LONG CHÂU CRAWLER LOG")
    print("=" * 100)

    for line in logs:
        print(line)


def item_address(item):
    location = item.get("location") or {}
    return (
        location.get("addressDisplay")
        or location.get("address")
        or ""
    ).strip()


def item_phone(item):
    item = item or {}
    location = item.get("location") or {}
    return (
        item.get("phone")
        or item.get("phoneNumber")
        or location.get("phone")
        or ""
    ).strip()


def item_coords(item):
    location = item.get("location") or {}
    coordinates = location.get("coordinates") or {}

    lat = (
        coordinates.get("lat")
        if isinstance(coordinates, dict)
        else ""
    )
    lon = (
        coordinates.get("lng")
        if isinstance(coordinates, dict)
        else ""
    )

    if lon in (None, "") and isinstance(coordinates, dict):
        lon = coordinates.get("long")

    return str(lat or ""), str(lon or "")


def item_summary(item):
    item = item or {}
    return {
        "shopCode": str(item.get("shopCode") or "").strip(),
        "shopName": str(item.get("shopName") or "").strip(),
        "address": item_address(item),
        "phone": item_phone(item),
        "slugEcom": str(
            item.get("slugEcom")
            or item.get("slug_Ecom")
            or ""
        ).strip(),
        "coordinates": item_coords(item),
    }


def count_unique(items, key_func):
    seen = set()

    for item in items:
        key = key_func(item)

        if key in (None, "", ()):
            continue

        seen.add(key)

    return len(seen)


def normalized_address(item):
    address = item_address(item)
    return normalize_text(address) if address else ""


def shop_code(item):
    return str(item.get("shopCode") or "").strip().lower()


def address_phone(item):
    address = normalized_address(item)
    phone = item_phone(item).lower()
    if not address:
        return None
    return address, phone


def code_address(item):
    code = shop_code(item)
    address = normalized_address(item)

    if not code and not address:
        return None

    return code, address


def print_duplicate_groups(items, key_name, key_func):
    groups = {}

    for index, item in enumerate(items):
        key = key_func(item)

        if key in (None, "", ()):
            continue

        groups.setdefault(key, []).append((index, item))

    duplicates = [
        (key, rows)
        for key, rows in groups.items()
        if len(rows) > 1
    ]

    print("\n" + "-" * 100)
    print(f"DUPLICATE GROUPS BY {key_name}")
    print("-" * 100)
    print(f"Duplicate groups: {len(duplicates)}")

    for group_no, (key, rows) in enumerate(duplicates, 1):
        print(f"\n[{group_no}] KEY = {key!r}")

        for index, item in rows:
            print(
                f"  raw_index={index} | "
                f"{item_summary(item)}"
            )

    return duplicates


async def collect_raw_longchau_api(start_url):
    """
    Independent diagnostic collector.

    It uses the same real browser XHR generated by clicking
    "Xem thêm nhà thuốc", but does NOT call crawl_longchau()'s
    production collector and does NOT dedupe API items.
    """

    payloads = []
    total_count = None

    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        context = await browser.new_context()
        page = await context.new_page()

        def is_store_api_response(response):
            return (
                response.request.method == "POST"
                and response.url.split("?", 1)[0] == LONGCHAU_STORE_API
            )

        async def capture_response(response):
            nonlocal total_count

            if not is_store_api_response(response):
                return

            try:
                payload = await response.json()
            except Exception:
                return

            if not isinstance(payload, dict):
                return

            if payload.get("items"):
                payloads.append(payload)

            if total_count is None and payload.get("totalCount") is not None:
                total_count = payload.get("totalCount")

        page.on("response", capture_response)

        try:
            print("\n" + "=" * 100)
            print("RAW API DIAGNOSTIC")
            print("=" * 100)
            print(f"Opening: {start_url}")

            await page.goto(
                start_url,
                wait_until="domcontentloaded",
                timeout=60000,
            )
            await page.wait_for_timeout(2000)

            body_text = await page.locator("body").inner_text()
            print(f"Page title: {await page.title()}")
            print(f"Body chars: {len(body_text)}")

            # Let any initial browser XHR finish before clicking.
            await page.wait_for_timeout(1500)

            for click_no in range(1, 201):
                api_items = [
                    item
                    for payload in payloads
                    for item in (payload.get("items") or [])
                    if isinstance(item, dict)
                ]

                if (
                    total_count is not None
                    and len(api_items) >= int(total_count)
                ):
                    print(
                        f"STOP: raw API item count {len(api_items)} "
                        f">= totalCount {total_count}"
                    )
                    break

                candidates = [
                    page.get_by_role(
                        "button",
                        name=re.compile(
                            r"Xem thêm nhà thuốc",
                            re.I,
                        ),
                    ).first,
                    page.get_by_text(
                        "Xem thêm nhà thuốc",
                        exact=True,
                    ).first,
                    page.locator(
                        "button:has-text('Xem thêm nhà thuốc')"
                    ).first,
                    page.locator(
                        "a:has-text('Xem thêm nhà thuốc')"
                    ).first,
                ]

                clicked = False

                for button in candidates:
                    try:
                        if not await button.is_visible(timeout=500):
                            continue

                        await button.scroll_into_view_if_needed(
                            timeout=2000
                        )

                        before = len(payloads)
                        await button.click(timeout=3000)

                        for _ in range(30):
                            if len(payloads) > before:
                                break
                            await page.wait_for_timeout(500)

                        if len(payloads) > before:
                            clicked = True
                        break

                    except Exception:
                        continue

                if not clicked:
                    print(
                        f"STOP: button not visible/clickable at click {click_no}"
                    )
                    break

            await page.wait_for_timeout(1000)

            api_items = [
                item
                for payload in payloads
                for item in (payload.get("items") or [])
                if isinstance(item, dict)
            ]

            print(f"API payloads captured : {len(payloads)}")
            print(f"Raw API items         : {len(api_items)}")
            print(f"API totalCount        : {total_count}")

            return api_items, total_count

        finally:
            try:
                page.remove_listener(
                    "response",
                    capture_response,
                )
            except Exception:
                pass

            await browser.close()


def print_raw_api_analysis(items, total_count):
    print("\n" + "=" * 100)
    print("RAW API IDENTITY ANALYSIS")
    print("=" * 100)

    print(f"Raw API items                 : {len(items)}")
    print(f"API totalCount                : {total_count}")

    unique_code = count_unique(items, shop_code)
    unique_address = count_unique(items, normalized_address)
    unique_code_address = count_unique(items, code_address)
    unique_address_phone = count_unique(items, address_phone)

    print(f"Unique by shopCode            : {unique_code}")
    print(f"Unique by normalized address : {unique_address}")
    print(f"Unique by shopCode+address   : {unique_code_address}")
    print(f"Unique by address+phone      : {unique_address_phone}")

    print_duplicate_groups(
        items,
        "NORMALIZED ADDRESS",
        normalized_address,
    )

    print_duplicate_groups(
        items,
        "SHOP CODE",
        shop_code,
    )

    print("\n" + "-" * 100)
    print("WHAT THE CURRENT PRODUCTION DEDUPE WOULD DROP")
    print("-" * 100)

    seen_addresses = set()
    dropped = []

    for index, item in enumerate(items):
        address = normalized_address(item)

        if not address:
            continue

        if address in seen_addresses:
            dropped.append((index, item))
        else:
            seen_addresses.add(address)

    print(
        f"Items dropped by address-only dedupe: {len(dropped)}"
    )

    for index, item in dropped:
        print(
            f"  raw_index={index} | "
            f"{item_summary(item)}"
        )

    print("\n" + "-" * 100)
    print("INTERPRETATION")
    print("-" * 100)

    if len(items) == 501 and unique_address == 501:
        print(
            "API evidence: 501 raw items and 501 unique addresses. "
            "Address-based dedupe is not the source of the missing stores."
        )
    elif len(items) == 501 and unique_address == 497:
        print(
            "FOUND: API has 501 raw items, but address-only dedupe keeps "
            "only 497. The four dropped items are printed above."
        )
        print(
            "We should NOT change production dedupe until these four "
            "records are inspected."
        )
    elif total_count is not None and len(items) < int(total_count):
        print(
            "The browser diagnostic captured fewer API items than "
            "Long Châu reports in totalCount. This points to pagination/"
            "click timing rather than only a dedupe-key issue."
        )
    else:
        print(
            "The raw API shape differs from the earlier checkpoint. "
            "Use the duplicate groups and counts above to identify the "
            "correct store identity before changing production code."
        )


async def main():
    start_url = (
        sys.argv[1].rstrip("/")
        if len(sys.argv) > 1
        else DEFAULT_URL
    )

    print("=" * 100)
    print("LONG CHÂU ISOLATED TEST")
    print("=" * 100)
    print(f"URL: {start_url}")
    print()
    print("Production crawler code is NOT modified by this test.")
    print("Existing crawl_longchau() will be executed first.")
    print("A separate raw-API diagnostic will then inspect duplicates.")
    print()

    records, pages, logs = await crawl_longchau(start_url)

    print_log_lines(logs)

    print("\n" + "=" * 100)
    print("CHECKPOINT 1 - crawl_longchau()")
    print("=" * 100)
    print(f"Pages returned              : {len(pages)}")
    print(f"Records after local dedupe  : {len(records)}")

    final_records = dedupe_records(records)

    print("\n" + "=" * 100)
    print("CHECKPOINT 2 - generic dedupe_records()")
    print("=" * 100)
    print(f"Before generic dedupe       : {len(records)}")
    print(f"After generic dedupe        : {len(final_records)}")
    print(f"Records removed             : {len(records) - len(final_records)}")

    api_items, total_count = await collect_raw_longchau_api(start_url)
    print_raw_api_analysis(api_items, total_count)

    print("\n" + "=" * 100)
    print("END OF DIAGNOSTIC")
    print("=" * 100)
    print(
        "No production crawler file was changed by this diagnostic. "
        "Do NOT merge the current Long Châu dedupe change yet."
    )


if __name__ == "__main__":
    asyncio.run(main())
